### ISSUE TITLE
Demo app doesn't seem to render

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-phylogeny#4]
Demo: https://dash-phylogeny.herokuapp.com/

It's broken for me. Is it normal?

@TahiriNadia

**Comment by NadiaTahiri** [comment]
No, it works for me, could send me a screenshot @xhlulu please?

**Comment by xhlulu** [comment]
Nevermind, it seems to be good. Sorry about that!

**Comment by Saliva520319** [comment]
@NadiaTahiri could you put the css into a folder, seems in china, the css cdn doesnt work well. https://rawgit.com/  is not accessable.(Even i jump over the GW.

**Comment by xhlulu** [comment]
@Saliva520319 Thanks for pointing this out! Nadia is currently busy with a new development project so it might take her a bit of time to get this one done. However, you are highly encouraged to start a PR and use the new `asset` paradigm introduced in 0.22, as [described here](https://community.plot.ly/t/dash-version-0-22-0-released/12098).

It seems that all the css file are on Github, so you can download them: https://github.com/tahirinadia/styles/

**Comment by xhlulu** [comment]
Hope it was able to help! I'll close this issue for now, if you have any other question feel free to reopen it!
